### ISSUE TITLE
Can't connect to http://mikrohash.de/isf/api/v1.0/signin.php

### ISSUE THREAD

**Issue by ILayZ** [mikrohash/isf-jclient#13]
Hi!

Is this project alive?
I'm registered user, but can't run spammer jar.
Got error:

```
java -jar isf-jclient-1.0.6.jar

===== Welcome to the Spam Fund Java Client v1.0.6 ===←[0m
[16:05:37] [Configs]   ←[90m[DBG] loading configurations←[0m
[16:05:37] [Configs]   ←[90m[DBG] signing in using account: 'i.a.zaharchuk@gmail.com'←[0m
[16:05:38] [API-Mngr]  ←[1m←[33m[WRN] problem communicating with http://mikrohash.de/isf/api/v1.0/signin.php←[0m
[16:05:38] [API-Mngr]  ←[1m←[31m[ERR] Connection refused: connect←[0m
←[90m
java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at sun.net.NetworkClient.doConnect(Unknown Source)
        at sun.net.www.http.HttpClient.openServer(Unknown Source)
        at sun.net.www.http.HttpClient.openServer(Unknown Source)
        at sun.net.www.http.HttpClient.<init>(Unknown Source)
        at sun.net.www.http.HttpClient.New(Unknown Source)
        at sun.net.www.http.HttpClient.New(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source)
        at isf.APIManager.request(APIManager.java:36)
        at isf.APIManager.keepSendingUntilSuccess(APIManager.java:128)
        at isf.Configs.load(Configs.java:107)
        at isf.Configs.loadWini(Configs.java:212)
        at isf.Configs.loadOrGenerate(Configs.java:26)
        at isf.Main.main(Main.java:15)
←[0m
[16:05:40] [API-Mngr]  ←[1m←[33m[WRN] signing in failed (could not access 'http://mikrohash.de/isf/api/v1.0/signin.php', please check your internet connection), tryi
ng again in 5 seconds←[0m
```

But when I run this URL in browser:
[https://mikrohash.de/isf/api/v1.0/signin.php](https://mikrohash.de/isf/api/v1.0/signin.php?email=i.a.zaharchuk@gmail.com&nonce=&hash=69aca0fcb6aaec0d93d0c19862ee7e67)

I got JSON
```
{
  "success": false,
  "error": "you are out of sync (lacking 1519910105 seconds behind), trying again in a few seconds",
  "nonce": 1519910105,
  "error_id": -1
}
```

So, at least that's not internet connection problem.

Can you help me?

BR, ILay

**Comment by vuapo-eth** [comment]
Does this error occur every time you start the spammer? Even after letting it run for a minute? If so, it might be your firewall which allows you to open the website in your browser, but does not allow the .jar file to do so.

**Comment by vuapo-eth** [comment]
v1.0.7 will now tell you whether it only has problems connecting to mikrohash.de or if it also fails to connect to coinmarketcap.com.

**Comment by ILayZ** [comment]
Confirm, it's firewall. Close the issue.
