### ISSUE TITLE
Crash while writing logfile

### ISSUE THREAD

**Issue by svenger87** [mikrohash/isf-jclient#2]
Spammer crashes constantly while trying to write logfile on Windows 10 and Ubuntu Xenial:

> [17:12:18] [FileMngr]  [1m[31m[ERR] C:\Users\Admin\Desktop\spammer\logs\2018-02-08_17-11-18.txt (Das System kann den angegebenen Pfad nicht finden)[0m
[90m
java.io.FileNotFoundException: C:\Users\Admin\Desktop\spammer\logs\2018-02-08_17-11-18.txt (Das System kann den angegebenen Pfad nicht finden)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at iota.FileManager.write(FileManager.java:96)
        at iota.ui.UIManager.saveLogs(UIManager.java:65)
        at iota.ui.UIManager.print(UIManager.java:51)
        at iota.ui.UIManager.logPln(UIManager.java:75)
        at iota.ui.UIManager.logInf(UIManager.java:78)
        at iota.LogThread.run(LogThread.java:59)
[0m
[17:12:18] [FileMngr]  [90m[DBG] program will be terminated now due to above error[0m

**Comment by vuapo-eth** [comment]
should be fixed in v1.0.1

**Comment by svenger87** [comment]
Nope. Sadly not. logs directory is next to binary file.:

![image](https://user-images.githubusercontent.com/35897839/35988262-41efed3c-0cfe-11e8-93f8-0c62cce3b4dd.png)

**Comment by vuapo-eth** [comment]
v1.0.2 should do it! :smile:

**Comment by svenger87** [comment]
Fixed :)
