### ISSUE TITLE
[FileMngr]  [ERR] No such file or directory

### ISSUE THREAD

**Issue by jgordor** [mikrohash/isf-jclient#4]
After some time of running:

```
[17:30:51] [ISF-API]   [INF] IOTA TICKER:     $1.79/Mi (+0.98% in 24h)     21,702 sat/Mi     MCAP: $4.97B (#10)
[17:30:52] [LogThrd]   [INF] TIME 0:00:00:00 | SPAM       3 txs | SPEED  0.00 txs/min | CNFMD   0/3   txs (00.00%) | BLNCE 0i ($0.00) | EST. RWRD  0.00 Mi ($0.00) per month
[17:31:52] [LogThrd]   [INF] TIME 0:00:01:00 | SPAM       8 txs | SPEED  4.97 txs/min | CNFMD   0/3   txs (00.00%) | BLNCE 0i ($0.00) | EST. RWRD  0.00 Mi ($0.00) per month
[17:31:52] [FileMngr]  [ERR] No such file or directory

java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at iota.FileManager.write(FileManager.java:97)
	at iota.ui.UIManager.saveLogs(UIManager.java:65)
	at iota.ui.UIManager.print(UIManager.java:51)
	at iota.ui.UIManager.logPln(UIManager.java:75)
	at iota.ui.UIManager.logInf(UIManager.java:78)
	at iota.LogThread.run(LogThread.java:59)

[17:31:52] [FileMngr]  [DBG] program will be terminated now due to above error
```

**Comment by vuapo-eth** [comment]
thanks for reporting :+1: 
please try v1.0.2 and report back

**Comment by jgordor** [comment]
Thanks @mikrohash the release page don't has the compiled client, can you upload it please?

**Comment by vuapo-eth** [comment]
uploaded :smile:

**Comment by jgordor** [comment]
Thanks! Seems fixed
